sudo: required
services: 
  - docker

# using dev docker file for testing only in pre install step
before_install:
  - docker build -t manojm95/react-test -f ./client/Dockerfile.dev ./client

# -- -- coverage is to break the wait after npm run test
script:
  - docker run manojm95/react-test npm test -- --coverage

after_success:
  - docker build -t manojm95/multi-client ./client
  - docker build -t manojm95/multi-nginx ./nginx
  - docker build -t manojm95/multi-server ./server
  - docker build -t manojm95/multi-worker ./worker

#Login to docker cli to push above images to docker hub
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin

#PUSH all built images
  - docker push manojm95/multi-client
  - docker push manojm95/multi-nginx
  - docker push manojm95/multi-server
  - docker push manojm95/multi-worker
